algoritmo "calcula-media"

var
   p1,p2,p3,p4, media:real

inicio

      escreval("Calcula média final")
      escreval("Insira a nota P1:")
      leia(P1)
      escreval("Insira a nota P2:")
      leia(P2)
      escreval("Insira a nota P3:")
      leia(P3)
      escreval("Insira a nota P4:")
      leia(P4)
      //calcula a media
      media <-(p1+p2+p3+p4)/4
      Escreval("O resultado final das provas: ", media)
      
fimalgoritmo
